_wandb:
    value:
        cli_version: 0.22.2
        e:
            n94le6dw71ln4qzvl62vipjsrtswq52c:
                codePath: ppo/ppo.ipynb
                codePathLocal: ppo.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "269427478528"
                        used: "41308377088"
                email: martinacarrettab@gmail.com
                executable: /bin/python3
                git:
                    commit: 048222afc5f9f612f5150af9df102a6830fa1086
                    remote: https://github.com/Martinacarretta/tfg
                host: LAPTOP-INQT65B2
                memory:
                    total: "3991113728"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/martina/codi2/4year/tfg/ppo/ppo.ipynb
                python: CPython 3.10.12
                root: /home/martina/codi2/4year/tfg/ppo
                startedAt: "2025-12-04T18:40:48.147477Z"
                writerId: n94le6dw71ln4qzvl62vipjsrtswq52c
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 35
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
                - 2
            "12": 0.22.2
            "13": linux-x86_64
algo:
    value: PPO
envs:
    value: 8
