_wandb:
    value:
        cli_version: 0.22.2
        e:
            tps6cziqnmof4cpzoz97caw4goauhgnr:
                codePath: training.ipynb
                codePathLocal: training.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "269427478528"
                        used: "39668776960"
                email: martinacarrettab@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: a54a465fc86a0bb40ed9795355171be7f5134c0a
                    remote: https://github.com/Martinacarretta/tfg
                host: LAPTOP-INQT65B2
                memory:
                    total: "3991109632"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/martina/codi2/4year/tfg/training.ipynb
                python: CPython 3.10.12
                root: /home/martina/codi2/4year/tfg
                startedAt: "2025-11-03T21:06:38.869125Z"
                writerId: tps6cziqnmof4cpzoz97caw4goauhgnr
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 16
                - 61
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
                - 2
            "12": 0.22.2
            "13": linux-x86_64
BATCH_SIZE:
    value: 128
BURN_IN:
    value: 1000
DNN_SYNC:
    value: 20
DNN_UPD:
    value: 1
Decay type:
    value: subtraction
EPSILON:
    value: 0.7
EPSILON_DECAY:
    value: 0.007776666666666666
EPSILON_MIN:
    value: 0.0001
GAMMA:
    value: 0.99
MAX_EPISODES:
    value: 90
MEMORY_SIZE:
    value: 15000
cnn structure:
    value:
        activation: ELU
        fc layers:
            - 512
            - 256
            - 128
            - 3
        filters:
            - 32
            - 32
            - 32
            - 32
        kernel_size: 3
        optimizer: Adam
        padding: 1
        stride: 2
lr:
    value: 0.0001
reward:
    value:
        - 10
        - -2
        - -0.5
