_wandb:
    value:
        cli_version: 0.22.2
        e:
            obfva5ndzabj6zvyv39yvwtvmgehrp2w:
                codePath: training.ipynb
                codePathLocal: training.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "269427478528"
                        used: "39842525184"
                email: martinacarrettab@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: 31c11255c5c70b9dc8e4e3501c1f19e676d230a1
                    remote: https://github.com/Martinacarretta/tfg
                host: LAPTOP-INQT65B2
                memory:
                    total: "3991105536"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/martina/codi2/4year/tfg/training.ipynb
                python: CPython 3.10.12
                root: /home/martina/codi2/4year/tfg
                startedAt: "2025-11-05T16:02:45.584326Z"
                writerId: obfva5ndzabj6zvyv39yvwtvmgehrp2w
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 16
                - 61
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
                - 2
            "12": 0.22.2
            "13": linux-x86_64
BATCH_SIZE:
    value: 128
BURN_IN:
    value: 1000
DNN_SYNC:
    value: 20
DNN_UPD:
    value: 1
Decay type:
    value: subtraction
EPSILON:
    value: 0.6
EPSILON_DECAY:
    value: 0.006665555555555556
EPSILON_MIN:
    value: 0.0001
GAMMA:
    value: 0.99
MAX_EPISODES:
    value: 90
MEMORY_SIZE:
    value: 15000
cnn structure:
    value:
        activation: ELU
        fc layers:
            - 512
            - 256
            - 128
            - 3
        filters:
            - 32
            - 32
            - 32
            - 32
        kernel_size: 3
        optimizer: Adam
        padding: 1
        stride: 2
lr:
    value: 0.0001
reward:
    value:
        - 10
        - -2
        - -0.5
