_wandb:
    value:
        cli_version: 0.22.2
        e:
            9x9p2m55ghrx9h9us5l1lxn7f8jj984o:
                codePath: reference.ipynb
                codePathLocal: reference.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "269427478528"
                        used: "39665152000"
                email: martinacarrettab@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: a54a465fc86a0bb40ed9795355171be7f5134c0a
                    remote: https://github.com/Martinacarretta/tfg
                host: LAPTOP-INQT65B2
                memory:
                    total: "3991109632"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/martina/codi2/4year/tfg/reference.ipynb
                python: CPython 3.10.12
                root: /home/martina/codi2/4year/tfg
                startedAt: "2025-11-03T15:03:05.943570Z"
                writerId: 9x9p2m55ghrx9h9us5l1lxn7f8jj984o
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
                - 2
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 128
episodes:
    value: 90
epsilon_decay:
    value: 0.0001
epsilon_min:
    value: 0.0001
epsilon_start:
    value: 0.7
gamma:
    value: 0.99
lr:
    value: 0.0001
