_wandb:
    value:
        cli_version: 0.22.2
        e:
            dnvqfk05ki2r88pzkdoebazy3g9fnnjc:
                codePath: training.ipynb
                codePathLocal: training.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "269427478528"
                        used: "40694775808"
                email: martinacarrettab@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: 97d76728f870a8f55a83299fb5fb16e29bcc4c55
                    remote: https://github.com/Martinacarretta/tfg
                host: LAPTOP-INQT65B2
                memory:
                    total: "3991109632"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/martina/codi2/4year/tfg/training.ipynb
                python: CPython 3.10.12
                root: /home/martina/codi2/4year/tfg
                startedAt: "2025-11-12T12:18:02.342686Z"
                writerId: dnvqfk05ki2r88pzkdoebazy3g9fnnjc
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 16
                - 61
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
                - 2
            "12": 0.22.2
            "13": linux-x86_64
BATCH_SIZE:
    value: 32
BURN_IN:
    value: 500
DNN_SYNC:
    value: 20
DNN_UPD:
    value: 2
Decay type:
    value: exponential
EPSILON:
    value: 1
EPSILON_DECAY:
    value: 0.98
EPSILON_MIN:
    value: 0.1
GAMMA:
    value: 0.9
MAX_EPISODES:
    value: 90
MEMORY_SIZE:
    value: 10000
agent:
    value: DQNAgent2
buffer:
    value: ReplayBuffer2
configuration:
    value:
        action_space: Discrete(3)
        grid_size: 4
        rewards:
            - 15
            - -2
            - -1
environment:
    value: Glioblastoma2
lr:
    value: 1e-05
model:
    value: DQN3
notes:
    value: discrete(3)
