_wandb:
    value:
        cli_version: 0.22.2
        e:
            3stbdjg2icebont321871byr2y7qfhe6:
                codePath: training.ipynb
                codePathLocal: training.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "269427478528"
                        used: "41265774592"
                email: martinacarrettab@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: f03de68efb89dcd83c15325dd0d5186f8ff0d18e
                    remote: https://github.com/Martinacarretta/tfg
                host: LAPTOP-INQT65B2
                memory:
                    total: "3991105536"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/martina/codi2/4year/tfg/training.ipynb
                python: CPython 3.10.12
                root: /home/martina/codi2/4year/tfg
                startedAt: "2025-11-12T22:06:45.200703Z"
                writerId: 3stbdjg2icebont321871byr2y7qfhe6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 14
                - 16
                - 61
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
                - 2
            "12": 0.22.2
            "13": linux-x86_64
BATCH_SIZE:
    value: 128
BURN_IN:
    value: 500
DNN_SYNC:
    value: 20
DNN_UPD:
    value: 1
Decay type:
    value: exponential
EPSILON:
    value: 1
EPSILON_DECAY:
    value: 0.95
EPSILON_MIN:
    value: 0.1
GAMMA:
    value: 0.9
MAX_EPISODES:
    value: 90
MEMORY_SIZE:
    value: 15000
agent:
    value: DQNAgent2
buffer:
    value: ReplayBuffer
configuration:
    value:
        action_space: Discrete(3)
        grid_size: 4
        rewards:
            - 1
            - -2
            - -0.5
environment:
    value: Glioblastoma2
lr:
    value: 0.0001
model:
    value: DQN2
notes:
    value: Retry last run with positional encoding
