_wandb:
    value:
        cli_version: 0.22.2
        e:
            iz9d3ihpvasgpawi3xnpgdrh7dxawi57:
                codePath: training.ipynb
                codePathLocal: training.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "269427478528"
                        used: "39626997760"
                email: martinacarrettab@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: d7f93acce72ef6689a9bbab32e4733a45b5dbfe5
                    remote: https://github.com/Martinacarretta/tfg
                host: LAPTOP-INQT65B2
                memory:
                    total: "3991113728"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/martina/codi2/4year/tfg/training.ipynb
                python: CPython 3.10.12
                root: /home/martina/codi2/4year/tfg
                startedAt: "2025-11-01T21:50:13.325426Z"
                writerId: iz9d3ihpvasgpawi3xnpgdrh7dxawi57
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
                - 2
            "12": 0.22.2
            "13": linux-x86_64
BATCH_SIZE:
    value: 128
BURN_IN:
    value: 1000
DNN_SYNC:
    value: 20
DNN_UPD:
    value: 1
EPSILON:
    value: 1
EPSILON_DECAY:
    value: 0.95
EPSILON_MIN:
    value: 0.1
GAMMA:
    value: 0.99
MAX_EPISODES:
    value: 100
MEMORY_SIZE:
    value: 15000
cnn:
    value:
        filters:
            - 32
            - 64
            - 128
        kernel_size: 3
        pool_size: 2
lr:
    value: 0.0001
