_wandb:
    value:
        cli_version: 0.22.2
        e:
            db8qxjolbnkyb11x8vfhfuu7grl3z63a:
                codePath: training.ipynb
                codePathLocal: training.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "269427478528"
                        used: "39172280320"
                email: martinacarrettab@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: 1b4a2198804ceebada6a612684377c34592f801d
                    remote: https://github.com/Martinacarretta/tfg
                host: LAPTOP-INQT65B2
                memory:
                    total: "3991113728"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/martina/codi2/4year/tfg/training.ipynb
                python: CPython 3.10.12
                root: /home/martina/codi2/4year/tfg
                startedAt: "2025-10-20T22:29:01.800753Z"
                writerId: db8qxjolbnkyb11x8vfhfuu7grl3z63a
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
                - 61
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
                - 2
            "12": 0.22.2
            "13": linux-x86_64
BATCH_SIZE:
    value: 128
BURN_IN:
    value: 1000
DNN_SYNC:
    value: 200
DNN_UPD:
    value: 1
EPSILON:
    value: 0.7
EPSILON_DECAY:
    value: 0.0001
EPSILON_MIN:
    value: 0.0001
GAMMA:
    value: 0.99
MAX_EPISODES:
    value: 90
MEMORY_SIZE:
    value: 15000
lr:
    value: 0.0001
