_wandb:
    value:
        cli_version: 0.22.2
        e:
            x2xybb86w13tatewfl328mu1mf2gur41:
                codePath: ppo/ppo.ipynb
                codePathLocal: ppo.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "269427478528"
                        used: "41064439808"
                email: martinacarrettab@gmail.com
                executable: /bin/python3
                git:
                    commit: 6c69e9168e5c309871c26f9d97db7fb1e7657bbe
                    remote: https://github.com/Martinacarretta/tfg
                host: LAPTOP-INQT65B2
                memory:
                    total: "3991105536"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/martina/codi2/4year/tfg/ppo/ppo.ipynb
                python: CPython 3.10.12
                root: /home/martina/codi2/4year/tfg/ppo
                startedAt: "2025-11-13T23:17:23.709607Z"
                writerId: x2xybb86w13tatewfl328mu1mf2gur41
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
                - 2
            "12": 0.22.2
            "13": linux-x86_64
batch_size:
    value: 128
configuration:
    value:
        action_space: Discrete(3)
        grid_size: 4
        rewards:
            - 5
            - -0.1
            - -0.02
learning_rate:
    value: 0.0001
max_episodes:
    value: 1000
num_steps:
    value: 512
